### ISSUE TITLE
Pre-audit Checklist

### ISSUE THREAD

**Issue by apollo-sturdy** [apollodao/cw-dex-router#4]
Blocked by #3, #5, #6

DoD: Make sure everything from this [checklist](https://github.com/oak-security/resources/blob/main/checklists/CosmWasm%20Smart%20Contract%20Audit%20Checklist.pdf
) has been done:

- [x] #2 
- [x] Resolve any compiler warnings returned by cargo build
- [x] Apply rustfmt: `cargo fmt`
- [x] Resolve any issues returned by clippy by running `cargo clippy`
- [x] Ensure all tests of your project pass: `cargo test`
- [x] Ensure you have sufficient test coverage, e.g. through tarpaulin: `cargo tarpaulin -v`
- [x] Remove any files that are not specific to your project, e.g. Markdown files from a template you used
- [x] Remove any commented/unused code
- [x] Resolves any pending TODOs
- [x] Send us the repositories and commit hash that should be used for the audit (code freeze)
- [x] Specify the relevant directories/files in the repositories for the audit

**Comment by apollo-pacman** [comment]
Code freeze at `1db8457c7e7bb1dd093c086d8ef73e7105703343`
